'use client';

import { HugeiconsIcon } from '@hugeicons/react';
import {
  EyeIcon,
  MailIcon,
  LockIcon,
  ArrowRight01Icon,
  ArrowLeft01Icon,
  ArrowDown01Icon,
  ArrowUp01Icon,
  Building02Icon,
  UserIcon,
  Home01Icon,
  UserGroupIcon,
  Globe02Icon,
  Shield01Icon,
  CallIcon,
  MapPinIcon,
  Clock01Icon,
  Menu01Icon,
  Cancel01Icon,
  Search01Icon,
  CheckmarkCircle01Icon,
  Delete02Icon,
  Edit01Icon,
  Add01Icon,
  StarIcon,
  Notification02Icon,
  SmartPhone01Icon,
  RefreshIcon,
  SparklesIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  HeartAddIcon,
  DashboardSquare01Icon,
} from '@hugeicons/core-free-icons';

export {
  HugeiconsIcon,
  EyeIcon,
  MailIcon,
  LockIcon,
  ArrowRight01Icon,
  ArrowLeft01Icon,
  ArrowDown01Icon,
  ArrowUp01Icon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  Building02Icon,
  UserIcon,
  Home01Icon,
  UserGroupIcon,
  Globe02Icon,
  Shield01Icon,
  CallIcon,
  MapPinIcon,
  Clock01Icon,
  Menu01Icon,
  Cancel01Icon,
  Search01Icon,
  CheckmarkCircle01Icon,
  Delete02Icon,
  Edit01Icon,
  Add01Icon,
  StarIcon,
  Notification02Icon,
  SmartPhone01Icon,
  RefreshIcon,
  SparklesIcon,
  HeartAddIcon,
  DashboardSquare01Icon,
};

// Re-export as Icon for convenience
export const Icon = HugeiconsIcon;
